### ISSUE TITLE
usage directions fail at npm install babel-node

### ISSUE THREAD

**Issue by Terrycoco** [catamphetamine/react-website#59]
npm install babel-node error.  Get message 
babel-node@6.5.3 postinstall: 'node message.js: sleep 10; exit 1;'

┌─────────────────────────────────────────────────────────────────────────────┐
|                         Hello there undefined 😛                           │
|          You tried to install babel-node. This is not babel-node 🚫          │
|               You should npm install -g babel-cli instead 💁 .               │
|    I took this module to prevent somebody from pushing malicious code. 🕵    │
|                    Be careful out there, undefined! 👍                     │
└─────────────────────────────────────────────────────────────────────────────┘

**Comment by catamphetamine** [comment]
Oh, thx, ok, changed it to `npm install babel-cli`.
I guess that one works.
