### ISSUE TITLE
react-router problem

### ISSUE THREAD

**Issue by lamyat2005** [catamphetamine/react-website#61]
Hi, previously I was using react-router like `<Router /> `to wrap the `<Routes />` and it worked well, however seems the new version no longer supports my use of `<Router />`, just wondering how I should do to wrap my `<Routes />` ? Thanks.

**Comment by catamphetamine** [comment]
The older versions didn't allow `<Router/>` too.
Perhaps some ancient ones did, but that would be more than a year before now.
No need to specify any `<Router/>` element, just pass the root `<Route/>` to it.
If any questions arise post them in this thread.
I'm closing it for now.

**Comment by lamyat2005** [comment]
I have a login component `RequiredRole` added to my `<Route>` like this
`<Route
      component={RequireRole}
      requiredRole={[ROLE_PUBLIC, ROLE_USER]}
      <Route path="/" component={LandingPage} />
</Route>`

and in my RequiredRole component is like this
`
function pathForUserNotPermitted(currentRole, requiredRoles, redirectMap) {
  const notPermitted = requiredRoles.indexOf(currentRole) === -1;
  return notPermitted ? redirectMap[currentRole] : undefined;
}

class RequireRole extends Component {
  static propTypes = {
    'route': PropTypes.object.isRequired,
    'children': PropTypes.any,
    'location': PropTypes.object.isRequired,
    'dispatch': PropTypes.func.isRequired,
    'auth': PropTypes.object,
    'routing': PropTypes.object.isRequired,
  };

  static contextTypes = {
    'router': PropTypes.object.isRequired,
  };

  componentWillMount() {
    // For first time getting to component, componentWillMount will be triggered.
    const nextPath = pathForUserNotPermitted(
      this.props.auth.role,
      this.props.route.requiredRole,
      this.props.route.redirectMap
    );

    // permission checking
    if (nextPath) {
      this.context.router.replace(nextPath);
    }
  }
...
`

Just wondering will my RequiredRole component still work if I pass down to `<Route>`? Thanks.

**Comment by catamphetamine** [comment]
Format the source code appropriately

**Comment by lamyat2005** [comment]
Just formatted, thanks.

**Comment by catamphetamine** [comment]
It should work.
Try it.
It would be much quicker if you just tested if it works instead of creating an issue and waiting for a reply.
I didn't test such scenarios but `router` should be present in `context`.

**Comment by catamphetamine** [comment]
If you're interested which Authentication and Authorization scheme I'm using here's a description:
https://github.com/catamphetamine/react-website#http-authentication

There are some technical details which are rather complex but for now it's how it works where I work.

**Comment by lamyat2005** [comment]
Thanks for suggestions, I'll have a look.
