### ISSUE TITLE
Http utility in Server Side

### ISSUE THREAD

**Issue by vetrslav** [catamphetamine/react-website#63]
Hi, 

I want to use redux thunk, with react-website, and i want to use http utility inside redux-thunk functions and preload some data on server side. And as i understand, currently it is possible to import  http utility only on client side.
Could you please advise me some solution for this in case i have missed something important or just add some simple functionality to enable universal http utility importing ?

**Comment by catamphetamine** [comment]
Why do you think `http` is only available on client side?

**Comment by catamphetamine** [comment]
> I know that it's universal but as I understand this utility is avilable only in your middleware for async actions, and i want something like this in redux-thunk

I see.
Well, there is no `global` variable on server-side so `getHttpClient()` doesn't work there.
Instead, `http` client could be stored somewhere in `store`, like `store.httpClient = httpClient` but then how would one access `store` from an action... I guess it's not correct to access `store` from an action. In Redux, there's no way actually to access `store` directly, only `getState()`, but `httpClient` can't be stored in state because it's not a JSON object.

**Comment by catamphetamine** [comment]
I'll close this for now as "not possible".
Still you can write comments here.

**Comment by vetrslav** [comment]
ok, thanks
Yeah, that's it
I found something like workaround for this
workaround is to export some global variable (for example **httpUtility**) in _source / redux / store.js_
and to set 
**httpUniversal = http_client** 
inside **create_store** function
it solves my needs
But i want it to be in npm package
Could you please add this in new version?
I think that this workaround is ok as i understand because we will use httpUtility always after the store is created
and it always gonna return correct http utility as on client and as on server

**Comment by catamphetamine** [comment]
I don't understand, which exact variable do you set inside create_store function.
You can post some actual code.

**Comment by vetrslav** [comment]
![image](https://user-images.githubusercontent.com/20933356/38455035-b4030ca2-3a7a-11e8-833d-da070cdd4299.png)
something like this in _source / redux / store.js_

**Comment by catamphetamine** [comment]
You can't share an `httpClient` between several users.
If you store it in a global variable then many users are using it simultaneously.
It's not supposed to be used like that: it should be constructed anew for each page for each user.

**Comment by vetrslav** [comment]
I get it, ok i will use common react-website approach for async actions.
thanks :)

**Comment by catamphetamine** [comment]
You should be able to do anything using the common react-website approach for async actions.
If there's a use-case where something is not possible then you can post it here.

**Comment by vetrslav** [comment]
ok, thanks
