### ISSUE TITLE
how can i run this site?

### ISSUE THREAD

**Issue by VishalChauha** [catamphetamine/react-website#64]
i am new to react website.
i have downloaded this project and try to run with webstrom but 'npm start' command is not working.
can you help me?
thanks

**Comment by catamphetamine** [comment]
post a screenshot

**Comment by VishalChauha** [comment]
here is the screenshot attached
![gitupload](https://user-images.githubusercontent.com/12601237/39519753-b796b3aa-4e25-11e8-9104-8fbc4aa18361.png)

**Comment by catamphetamine** [comment]
No, the screenshot of the error.

**Comment by VishalChauha** [comment]
no there is no error but when i try to run website i got this (as you can see in 'terminal' window).
and nothing happened.

**Comment by catamphetamine** [comment]
Which "website" are you "running"?
This is not a "website".
This is a library.

**Comment by VishalChauha** [comment]
my bad, i am new to react so don't know how to make it run like http://www.myreactwebsite.com.
closing this issue

**Comment by catamphetamine** [comment]
You can't make it run because it's not a website.
The name is "react-website" but it's not a website, it's a library for building a website.
See https://github.com/catamphetamine/react-website-basic-example

**Comment by VishalChauha** [comment]
Thanks for your help
