### ISSUE TITLE
How modify @preload {client: true} configuration

### ISSUE THREAD

**Issue by davidwalker2235** [catamphetamine/react-website#65]
Hello.

I can't find how modify the @preload configuration for turn {client: true} for preload the pages on client side.
I should do it in react-website.js file?... how?

Thanks

**Comment by catamphetamine** [comment]
It's unclear what you mean.
Explain your situation.

**Comment by davidwalker2235** [comment]
I have a problem with the @preload method.
I have a login page and when I click on "login" and the response is success I change the page to a new initial page but the @preload decorator it doesn't work because the page is loaded in client-side.
How I can configure the @preload for use it on client-side?

In the documentation says:
"client — If true then the @preload() will be executed only on client side. If false then this @preload() will be executed normally: if part of initial page preloading then on server side and if part of subsequent preloading (e.g. navigation) then on client side. false is the default value unless overridden by preload.client configuration parameter."

but I didn't find where I can change this option.

**Comment by catamphetamine** [comment]
> How I can configure the @preload for use it on client-side?

Passing `{ client: true }` to preload makes it only work on client-side.
If you think you caught a bug then you can provide a video illustrating an issue (or provide a sample repo with instructions).

**Comment by davidwalker2235** [comment]
Ok thanks, but How can I pass { client: true } to the preload?.. where? Inside the @preload like this?:

@preload(async (preloadOptions) => {
     preloadOptions = { ...preloadOptions, client: true }
     return await store.dispatch(getMainData(preloadOptions))
})

Sorry, but I'm blocked and I'm not finding any solution

**Comment by catamphetamine** [comment]
aaaah, that's what is unclear to you.
I'll add an example to readme.
the way is:

```js
@preload(async () => { ... }, { client: true })
```
