### ISSUE TITLE
How to capture an event type

### ISSUE THREAD

**Issue by davidwalker2235** [catamphetamine/react-website#66]
I need an action wich execute one type of event and then this type fires two reducers.
For example:

I have this action in the reducer "login":

const redux = reduxModule ('LOGIN');

export const getLoginData = redux.action
(
'GET_LOGIN',
async ({http}) =>
{
return {user: '', pass: ''}
},
'data'
)

and I want that the event type "GET_LOGIN" triggers a method in another reducer called "loading".
In the documentation I read that there is the option "redux.on ()" but it does not work.
In the reducer "loading" I declare it like this:

**redux.on (eventName ('LOGIN', 'GET_LOGIN'), (state, action) => {
debugger;
         console.log ('Go through the loading reducer')
         return state
     }
)**

which is supposed to capture the event type 'GET_LOGIN' from the reduxModule ('LOGIN'), but does nothing.
What am I doing wrong?

**Comment by catamphetamine** [comment]
> What am I doing wrong?

Nothing, it's just that you're listening on `LOGIN: GET_LOGIN` instead of `LOGIN: GET_LOGIN_SUCCESS`.
Install the latest version `react-website@2.0.21` and do:

```js
redux.on ('LOGIN', 'GET_LOGIN', (state, result) => {
  console.log ('Go through the loading reducer', result)
  return state
})
```

**Comment by davidwalker2235** [comment]
Done!! 

Thanks
