### ISSUE TITLE
No way to detect authentication before using http client

### ISSUE THREAD

**Issue by chris-allen** [catamphetamine/react-website#71]
### Scenario
I would imagine the use case is pretty common. You  wrap your entire application in a `@preload` that dispatches a redux action to fetch the logged-in user. The credentials for such a call come from configuration. Something like:

```javascript
authentication: {
  accessToken ({ getCookie }) {
    return getCookie('token');
  },
}
```

The magic here being that `getCookie` fetches client-side cookies and sets them as the `Authorization` header for every request (even server-side preloads :blush:) made by the http client.

### Problem
Obviously, the first time a user visits the site, there will be no `token` cookie.  This would cause the preload request to raise an exception (401 or something of that ilk).  My current hack is to catch the exception in the redux action. For example;

```javascript
export const getUser = redux.action(
  'GET_USER',
  () => async (http) => {
    try {
      return await http.get('/api/user/');
    } catch(e) {
      return null;
    }
  },
  'user'
);
```
This works, but generates unnecessary calls to `/api/user` on every initial page load - calls we shouldn't even make because there is no `token` cookie.  **_Unfortunately, there currently is no way to check if the above `accessToken` found anything._**

### Possible Solutions
I would love to hear if one of these solutions strikes your fancy more than the other:

1. Make the magic of `getCookie` available as a parameter in `@preload`. You could choose not to dispatch `getUser` if no token is present.
2. Expose the authorization headers on the http client itself making it possible for the redux action to no-op if it knows no header is present.

**Comment by catamphetamine** [comment]
Hi.
That's a good issue description, very informative.
I had something like this before (in 2016) but then I decided that React is too slow for server-side rendering (something like PHP is much faster I guess) so I dropped the feature.
Added `getCookie` parameter to `@preload()` in the latest version `react-website@3.1.25`.

**Comment by chris-allen** [comment]
Thanks so much for the quick update!
