### ISSUE TITLE
[SSR] Access to the request headers

### ISSUE THREAD

**Issue by bartushek** [catamphetamine/react-website#72]
I'm currently migrating from `react-isomorphic-render` to the newest version of `react-website` and I can't find any way to access request headers. Previously, I've used `initialize(httpClient, { request })` to obtain data from headers and save them in Redux state. What I am the most interested are the `accept-language` and `user-agent` headers, as our application is translated and renders different components based on UserAgent.

I've looked deeply through the source code, but I don't see any replacement method which could resolve my issue. Do you have any hint? Have I missed something or maybe could you add `request` to the `preload` params?

**Comment by catamphetamine** [comment]
See `getInitialState({ cookies, headers, locales })` in the latest version.

```js
export default function(parameters) {
  // Create webpage rendering server
  const server = webpageServer(settings, {
    getInitialState(options) {
      console.log(options)
      return {
        'a': 'b'
      }
    }
  })

  // Start webpage rendering server
  server.listen(configuration.services.rendering.port, function(error) {
    if (error) {
      console.error('Webpage rendering service was shut down due to an error')
      throw error
    }

    console.log(`Webpage rendering service is listening on port ${configuration.services.rendering.port}`)
  })
}
```

**Comment by catamphetamine** [comment]
Or maybe it's not working: I don't see the returned value in Redux state.
I'll check.

**Comment by catamphetamine** [comment]
No, seems to work.
The issue is that it outputs:

> Unexpected keys "a", "b", "c" found in preloadedState argument passed to createStore. Expected to find one of the known reducer keys instead: "users", "notifications", "found", "preload". Unexpected keys will be ignored.

But it seems to be Redux internal code.

**Comment by bartushek** [comment]
Yeah, it's normal for missing reducers.
Thanks for a quick response! It's working as intended 💯 🙇
